services:
  db:
    image: postgres:15-alpine
    container_name: todos-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: todos-backend
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432

  frontend:
    build: ./frontend
    container_name: todos-frontend
    ports:
      - "5174:5173"

volumes:
  postgres_data:
